import React, { useEffect, useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import * as Location from 'expo-location';
import { Camera } from 'expo-camera';
import { Accelerometer } from 'expo-sensors';
import { Audio } from 'expo-av';
import { DEFAULT_PLANS, SECURITY_FEATURES, loadPlans, saveSubscription, sendDeviceCommand } from './supabase';
const BLUE='#0A3D8A'; const ACTION_BLUE='#0A84FF';
async function requestPermissions(plan){const granted={}; if(plan.permissions.includes('camera')){const r=await Camera.requestCameraPermissionsAsync();if(r.status!=='granted')throw Error('Camera permission denied.');granted.camera=true;}if(plan.permissions.includes('location')){const r=await Location.requestForegroundPermissionsAsync();if(r.status!=='granted')throw Error('Location permission denied.');granted.location=true;}if(plan.permissions.includes('sensors')){const s=Accelerometer.addListener(()=>{});s.remove();granted.sensors=true;}if(plan.permissions.includes('microphone')){const r=await Audio.requestPermissionsAsync();if(r.status!=='granted')throw Error('Microphone permission denied.');granted.microphone=true;}return granted;}
export default function PlansScreen({onBack,deviceId='demo-device'}){const [plans,setPlans]=useState(DEFAULT_PLANS);const [busy,setBusy]=useState(null);const [open,setOpen]=useState({});useEffect(()=>{loadPlans().then(setPlans).catch(()=>{});},[]);const subscribe=async plan=>{setBusy(plan.name);try{const p=await requestPermissions(plan);const {error}=await saveSubscription({deviceId,plan,permissionsGranted:p});if(error)throw error;Alert.alert('Subscription active',`${plan.name} saved in Supabase.`);}catch(e){Alert.alert('Subscription failed',e.message||'Try again.');}finally{setBusy(null);}};const ring=async plan=>{const {error}=await sendDeviceCommand(deviceId,'RING');if(error)Alert.alert('Command failed',error.message);else Alert.alert('Command queued',`RING queued for ${plan.name}. A device agent must receive it.`);};return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Pressable style={styles.back} onPress={onBack}><Text style={styles.white}>Back</Text></Pressable><Text style={styles.title}>Security Plans</Text>{plans.map(plan=><View key={plan.name} style={styles.card}><Text style={styles.name}>{plan.name}</Text><Text style={styles.price}>K{plan.price}</Text><Pressable style={styles.tab} onPress={()=>setOpen(v=>({...v,[plan.name]:!v[plan.name]}))}><Text style={styles.tabText}>MISPLACED MODE {open[plan.name]?'▲':'▼'}</Text></Pressable>{open[plan.name]&&<View style={styles.box}><Text>Paid plans queue a RING command in Supabase. Device-side service is required to play sound.</Text>{plan.misplacedMode?<Pressable style={styles.ring} onPress={()=>ring(plan)}><Text style={styles.white}>RING MY PHONE</Text></Pressable>:<Text>Available on paid plans.</Text>}</View>}{SECURITY_FEATURES.map((f,i)=><Text key={f} style={styles.feature}>{plan.featureIndexes.includes(i)?'✅':'❌'} {f}</Text>)}<Pressable style={styles.button} onPress={()=>subscribe(plan)} disabled={!!busy}><Text style={styles.white}>{busy===plan.name?'SAVING...':`SUBSCRIBE K${plan.price}`}</Text></Pressable></View>)}</ScrollView>}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:BLUE},content:{padding:16,paddingBottom:40},back:{backgroundColor:ACTION_BLUE,padding:10,borderRadius:10,alignSelf:'flex-start',marginBottom:12},white:{color:'#fff',fontWeight:'800'},title:{color:'#fff',fontSize:30,fontWeight:'800',marginBottom:16},card:{backgroundColor:'#fff',borderRadius:16,padding:18,marginBottom:16},name:{color:BLUE,fontSize:23,fontWeight:'800'},price:{color:ACTION_BLUE,fontSize:28,fontWeight:'800'},tab:{backgroundColor:'#e9f2ff',padding:12,borderRadius:8,marginVertical:10},tabText:{color:BLUE,fontWeight:'800'},box:{backgroundColor:'#f5f9ff',padding:12,marginBottom:10},ring:{backgroundColor:BLUE,padding:12,borderRadius:8,marginTop:10,alignItems:'center'},feature:{color:'#172033',marginVertical:4},button:{backgroundColor:ACTION_BLUE,padding:14,borderRadius:10,alignItems:'center',marginTop:12}});
