import React, { useState } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, TextInput, View } from 'react-native';
import { supabase } from './supabase';
const BLUE='#0A3D8A'; const ACTION_BLUE='#0A84FF';
export default function RegisterScreen({ onBack, onLogin }) {
  const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState(''); const [busy,setBusy]=useState(false);
  const register=async()=>{ if(!name||!email||!password)return Alert.alert('Missing details','Complete all fields.'); setBusy(true); const {error}=await supabase.auth.signUp({email:email.trim(),password,data:{full_name:name.trim()}}); setBusy(false); if(error)return Alert.alert('Registration failed',error.message); Alert.alert('Check your email','Confirm your email before logging in.'); onLogin?.(); };
  return <ScrollView style={styles.screen} contentContainerStyle={styles.content}><Pressable style={styles.back} onPress={onBack}><Text style={styles.white}>Back</Text></Pressable><View style={styles.card}><Text style={styles.title}>Register</Text><TextInput style={styles.input} value={name} onChangeText={setName} placeholder="Full name"/><TextInput style={styles.input} value={email} onChangeText={setEmail} placeholder="Email" autoCapitalize="none" keyboardType="email-address"/><TextInput style={styles.input} value={password} onChangeText={setPassword} placeholder="Password" secureTextEntry/><Pressable style={styles.button} onPress={register} disabled={busy}><Text style={styles.white}>{busy?'CREATING...':'REGISTER'}</Text></Pressable><Pressable onPress={onLogin}><Text style={styles.link}>Already registered? Login</Text></Pressable></View></ScrollView>;
}
const styles=StyleSheet.create({screen:{flex:1,backgroundColor:BLUE},content:{padding:20},back:{backgroundColor:ACTION_BLUE,padding:10,borderRadius:10,alignSelf:'flex-start',marginBottom:18},white:{color:'#fff',fontWeight:'800'},card:{backgroundColor:'#fff',borderRadius:16,padding:20},title:{color:BLUE,fontSize:28,fontWeight:'800',marginBottom:16},input:{borderWidth:1,borderColor:'#d8e4f7',borderRadius:10,padding:12,marginBottom:14},button:{backgroundColor:ACTION_BLUE,padding:14,borderRadius:10,alignItems:'center'},link:{color:BLUE,textAlign:'center',fontWeight:'700',marginTop:16}});
